#!/bin/sh
#
# $OpenBSD: dnscrypt_proxy.rc,v 1.3 2016/02/04 14:29:25 sthen Exp $

daemon="/usr/local/bin/dnscrypt-proxy"

daemon_user="_dnscrypt-proxy"

. /etc/rc.d/rc.subr

rc_reload=NO

rc_start() {
	nohup su -l -c daemon -s /bin/sh ${daemon_user} -c "${daemon} ${daemon_flags}" > /dev/null 2>&1 &
}

rc_cmd $1

